import { readFile, writeFile } from "node:fs/promises";
import { dump, load } from "js-yaml";
import { corpusHash } from "@/lib/corpus/hash";
import type { AssertionReport } from "@/types/domain";

/**
 * The `emit` step (ADR-004): the corpus manifest.
 *
 * ⚠️ THIS FILE IS COMMITTED, and it ships under ADR-003 without difficulty: it
 * carries locators, hashes, counts and provenance, and not one word of corpus
 * text. Compare `corpus/errata/*.yaml`, which ships for exactly the same
 * reason.
 *
 * What it is for. A corpus refresh is a deliberate operator action, and ADR-004
 * asks that it leave an ARTEFACT rather than being an invisible background
 * process. Three things read this file:
 *
 *   * a human, asking what the deployed corpus actually contains;
 *   * `docs/evaluation.md`, which requires every eval report to record the
 *     corpus hash — so a retrieval number is tied to the corpus it was measured
 *     over, and a local run diverging from a CI run becomes visible rather than
 *     silent (ADR-004 § Trade-offs);
 *   * a future ingest, as the diff that shows what a re-fetch changed.
 *
 * It is emitted per document and merged, so ingesting Hungarian does not
 * discard what a previous English run recorded.
 */

export const MANIFEST_PATH = "corpus/manifest.lock.yaml";

const HEADER = `# ── Apologia corpus manifest ────────────────────────────────────────────────
#
# GENERATED by \`npm run ingest\`. Do not edit by hand.
#
# The artefact ADR-004 asks a corpus refresh to leave behind: what was fetched,
# what it parsed to, and the hashes that tie an eval report to the exact corpus
# it was measured over.
#
# ⚠️ SHIPS UNDER ADR-003. Locators, hashes, counts and URLs only — no corpus
# text. \`content_hash\` is over the NORMALISED UNITS rather than the fetched
# HTML, so a re-theming of a source that changes no words does not present as a
# corpus revision; the per-page \`raw_hash\` values answer the separate question
# of what exactly was downloaded.
`;

export interface EmittedDocument {
  sourceId: string;
  language: string;
  revision: string;
  edition: string | null;
  encoding: string;
  indexUrl: string;
  parser: string;
  chunking: string;
  contentHash: string;
  unitCount: number;
  chunkCount: number;
  pages: { slug: string; raw_hash: string }[];
  unnumberedPages: string[];
  skipped: Record<string, number>;
  report: AssertionReport;
}

interface ManifestFile {
  generated_at: string;
  corpus_hash: string;
  documents: Record<string, unknown>[];
}

function documentEntry(doc: EmittedDocument): Record<string, unknown> {
  return {
    source: doc.sourceId,
    language: doc.language,
    revision: doc.revision,
    edition: doc.edition,
    encoding: doc.encoding,
    index_url: doc.indexUrl,
    parser: doc.parser,
    chunking: doc.chunking,
    content_hash: doc.contentHash,
    unit_count: doc.unitCount,
    chunk_count: doc.chunkCount,
    // The assertion outcome, recorded so that "it ingested" and "it ingested
    // cleanly" are different statements a reader can tell apart later.
    assertions: {
      ok: doc.report.ok,
      undeclared: doc.report.undeclared.length,
      allowances_stale: doc.report.stale.length,
    },
    unnumbered_pages: doc.unnumberedPages,
    skipped: doc.skipped,
    pages: doc.pages,
  };
}

async function readExisting(path: string): Promise<ManifestFile | null> {
  try {
    const parsed = load(await readFile(path, "utf8"));
    return (parsed as ManifestFile) ?? null;
  } catch {
    return null;
  }
}

/**
 * Merge this run's document into the manifest and rewrite it.
 *
 * Merging rather than replacing is what lets `npm run ingest --language=hu`
 * leave the English entry alone. Documents are keyed by (source, language) and
 * sorted, so the file's diff shows what changed rather than how the keys
 * happened to be ordered.
 *
 * ── Emitted on every run, written only when the content differs ─────────────
 *
 * This used to be called only after a run that actually ingested, which left a
 * hole with no way out: upsert succeeds, `emitManifest` throws (disk full, bad
 * permissions), and the next run reports "unchanged — nothing to do" and
 * returns before reaching here. The manifest would never be written, and no
 * flag recovered it — `--refetch` re-downloads but produces the same hash, so
 * the run is still a no-op. Recovery meant deleting a document row by hand.
 *
 * Calling it unconditionally fixes that and creates a second problem: rewriting
 * `generated_at` on every no-op run makes a committed file dirty every time
 * anyone runs the ingest, which trains people to `git checkout` it.
 *
 * So the write is content-addressed like everything else here. The document
 * entries are compared against what is on disk, and the file is rewritten only
 * when they differ. A no-op run leaves the working tree untouched; a run whose
 * emit failed leaves the file stale, so the next run writes it.
 */
export async function emitManifest(
  doc: EmittedDocument,
  // Injectable so the write logic is testable without clobbering the real
  // manifest. Untestable file logic is where the recovery hole above came from.
  path: string = MANIFEST_PATH
): Promise<{ path: string; written: boolean }> {
  const existing = await readExisting(path);
  const others = (existing?.documents ?? []).filter(
    (entry) =>
      !(entry.source === doc.sourceId && entry.language === doc.language)
  );

  const documents = [...others, documentEntry(doc)].sort((a, b) =>
    `${a.source}:${a.language}`.localeCompare(`${b.source}:${b.language}`)
  );

  // `generated_at` is deliberately excluded from the comparison: it is metadata
  // about the run, not about the corpus, and including it would make every
  // no-op run a diff.
  if (
    existing !== null &&
    JSON.stringify(existing.documents) === JSON.stringify(documents)
  ) {
    return { path, written: false };
  }

  const manifest: ManifestFile = {
    generated_at: new Date().toISOString(),
    corpus_hash: corpusHash(
      documents.map((entry) => ({
        sourceId: entry.source as string,
        language: entry.language as string,
        contentHash: entry.content_hash as string,
      }))
    ),
    documents,
  };

  const yaml = dump(manifest, { lineWidth: 100, noRefs: true, sortKeys: false });
  await writeFile(path, `${HEADER}\n${yaml}`, "utf8");

  return { path, written: true };
}
